version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password 
      volumes:
        -C:/workspace/postgres-data:/var/lib/postgresql/data
      ports:
        -"db:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: email
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
