version: '3'

services:
  db:
    image: postgres
    environment:
      memory: 2g
      memory-swap: 3g
      POSTGRES_PASSWORD: password 
      volumes:
        -C:/workspace/postgres-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      memory: 2g
      memory-swap: 3g
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
